#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from libs.video import Video
from libs.audio import Audio
from libs.args import args


audio = ['mp3', 'ogg', 'aac', 'flac', '']
video = ['mp4', 'mkv', 'wmv', 'avi', 'flv',
         'mov', '3gp', 'vob', 'webm', 'wma', '']

if args.o == '':
    args.o = args.i
if args.O == '':
    args.O = args.I
if args.b != '':
    args.b = '-b:a ' + args.b
if args.t != '':
    args.t = '-ss ' + args.t[0] + ' -t ' + args.t[1]
else:
    args.t = ''

# Executed from for video
if args.I in video and args.O in video:
    video = Video(args.I, args.i, args.O, args.o, args.b, args.t, args.r)
    if not video.filter_files():
        print(f'\nThere is no .{video.input_midia_format} file(s) in {video.source_path}')
        exit()
    video.processing_file(video.filter_files())
    exit()

# Executed from for video/audio or audio
elif args.I in audio or args.I in video and args.O in audio:
    audio = Audio(args.I, args.i, args.O, args.o, args.b, args.t, args.r)
    audio.execute_files()
    exit()
